'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditOptionalPrices
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''frmEditPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmEditPrice As Global.DevExpress.Web.ASPxFormLayout
    
    '''<summary>
    '''ITEMNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ITEMNO As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''SERIALNUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SERIALNUM As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''C880USDDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USDDATE As Global.DevExpress.Web.ASPxDateEdit
    
    '''<summary>
    '''C880USD002 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USD002 As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''C880USD005 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USD005 As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''C880USD010 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USD010 As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''C880USD020 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USD020 As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''C880USD030 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USD030 As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''C880USD040 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USD040 As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''C880USD050 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USD050 As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''C880USD060 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USD060 As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''C880USD070 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USD070 As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''btnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEdit As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''sdsSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsSN As Global.System.Web.UI.WebControls.SqlDataSource
End Class
