'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class IC_SN
    
    '''<summary>
    '''popPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popPrice As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''frmEditPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmEditPrice As Global.DevExpress.Web.ASPxFormLayout
    
    '''<summary>
    '''ITEMNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ITEMNO As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''SERIALNUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SERIALNUM As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''C880USD002 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USD002 As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''C880USDDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USDDATE As Global.DevExpress.Web.ASPxDateEdit
    
    '''<summary>
    '''C880USD005 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USD005 As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''C880USD010 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USD010 As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''C880USD020 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USD020 As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''C880USD030 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USD030 As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''C880USD040 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USD040 As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''C880USD050 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USD050 As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''C880USD060 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USD060 As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''C880USD070 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C880USD070 As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''btnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEdit As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''ASPxGridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView1 As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''sdsCATEGORIES control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsCATEGORIES As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsRESVSLP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsRESVSLP As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''Exporter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Exporter As Global.DevExpress.Web.ASPxGridViewExporter
    
    '''<summary>
    '''sds640CARRIERS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds640CARRIERS As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds640CARRIERS2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds640CARRIERS2 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds640CARRIERS3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds640CARRIERS3 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds650PORTORIGS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds650PORTORIGS As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds720PORTLOADS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds720PORTLOADS As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds740OCEANCARRS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds740OCEANCARRS As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds760PORTDESTS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds760PORTDESTS As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds951CUSTSECT1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds951CUSTSECT1 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsC952CUSTSECT2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsC952CUSTSECT2 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsACCTSETS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsACCTSETS As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''LinqDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinqDataSource1 As Global.System.Web.UI.WebControls.LinqDataSource
    
    '''<summary>
    '''sdsItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsItems As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsARSAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsARSAP As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsSN As Global.System.Web.UI.WebControls.SqlDataSource
End Class
