'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class CRMXEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CRMXEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property GridLayouts() As DbSet(Of GridLayout)
    Public Overridable Property vUserPers() As DbSet(Of vUserPer)
    Public Overridable Property vCSOPTFHs() As DbSet(Of vCSOPTFH)
    Public Overridable Property UserGridLayouts() As DbSet(Of UserGridLayout)
    Public Overridable Property vSNs() As DbSet(Of vSN)
    Public Overridable Property vORDERS() As DbSet(Of vORDER)
    Public Overridable Property vOESHPDETAILS() As DbSet(Of vOESHPDETAIL)

    Public Overridable Function prUpdateOptValue(iTEMNUM As String, sERIALNUM As String, oPTFIELD As String, vALUE As String, aUDTDATE As Nullable(Of Integer)) As Integer
        Dim iTEMNUMParameter As ObjectParameter = If(iTEMNUM IsNot Nothing, New ObjectParameter("ITEMNUM", iTEMNUM), New ObjectParameter("ITEMNUM", GetType(String)))

        Dim sERIALNUMParameter As ObjectParameter = If(sERIALNUM IsNot Nothing, New ObjectParameter("SERIALNUM", sERIALNUM), New ObjectParameter("SERIALNUM", GetType(String)))

        Dim oPTFIELDParameter As ObjectParameter = If(oPTFIELD IsNot Nothing, New ObjectParameter("OPTFIELD", oPTFIELD), New ObjectParameter("OPTFIELD", GetType(String)))

        Dim vALUEParameter As ObjectParameter = If(vALUE IsNot Nothing, New ObjectParameter("VALUE", vALUE), New ObjectParameter("VALUE", GetType(String)))

        Dim aUDTDATEParameter As ObjectParameter = If(aUDTDATE.HasValue, New ObjectParameter("AUDTDATE", aUDTDATE), New ObjectParameter("AUDTDATE", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("prUpdateOptValue", iTEMNUMParameter, sERIALNUMParameter, oPTFIELDParameter, vALUEParameter, aUDTDATEParameter)
    End Function

End Class
