'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UserGridLayout
    Public Property ID As Integer
    Public Property UserId As Integer
    Public Property GridName As String
    Public Property LayoutName As String
    Public Property LayoutData As String
    Public Property Active As Nullable(Of Boolean)

End Class
