'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vOESHPDETAIL
    Public Property ID As Long
    Public Property CUSTOMER As String
    Public Property ITEM As String
    Public Property YR As String
    Public Property PR As Short
    Public Property TRANDATE As Nullable(Of Date)
    Public Property LINENO As Short
    Public Property TRANNUM As String
    Public Property TRANTYPE As Short
    Public Property ORDDATE As Nullable(Of Date)
    Public Property ORDNUMBER As String
    Public Property SHIPDATE As Nullable(Of Date)
    Public Property SALESPER As String
    Public Property TERRITORY As String
    Public Property TRANLOC As String
    Public Property CATEGORY As String
    Public Property QTYSOLD As Decimal
    Public Property SCURN As String
    Public Property FCSTSALES As Decimal
    Public Property FAMTSALES As Decimal
    Public Property FRETSALES As Decimal
    Public Property PONUMBER As String
    Public Property FAMTTRAN As Decimal
    Public Property SHINUMBER As String
    Public Property NAMECUST As String
    Public Property ITEMDESC As String

End Class
