'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vORDER
    Public Property ID As Long
    Public Property ORDUNIQ As Decimal
    Public Property ORDNUMBER As String
    Public Property CUSTOMER As String
    Public Property CUSTGROUP As String
    Public Property BILNAME As String
    Public Property BILPHONE As String
    Public Property BILCONTACT As String
    Public Property SHIPTO As String
    Public Property SHPNAME As String
    Public Property SHPPHONE As String
    Public Property SHPCONTACT As String
    Public Property PONUMBER As String
    Public Property OETYPE As Short
    Public Property DESC As String
    Public Property SALESPER1 As String
    Public Property SALESPER2 As String
    Public Property SALESPER3 As String
    Public Property SALESPER4 As String
    Public Property SALESPER5 As String
    Public Property OPPOID As Integer
    Public Property COMPANYID As Integer
    Public Property SHINUMBER As String
    Public Property INVNUMBER As String
    Public Property ORDDATE As Nullable(Of Date)
    Public Property SHIDATE As Nullable(Of Date)
    Public Property INVDATE As Nullable(Of Date)

End Class
