'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vSN
    Public Property ITEMNUM As String
    Public Property SERIALNUMF As String
    Public Property ITEMNO As String
    Public Property SERIALNUM As String
    Public Property C010FGWSN As String
    Public Property C020ENGINESN As String
    Public Property C030ALTSN As String
    Public Property C100FREQUENCY As Nullable(Of Integer)
    Public Property C110VOLTAGE As String
    Public Property C120PHASE As String
    Public Property C123AMPS As String
    Public Property C130KW As Nullable(Of Decimal)
    Public Property C133KW As Nullable(Of Decimal)
    Public Property C136KW As Nullable(Of Decimal)
    Public Property C139KW As Nullable(Of Decimal)
    Public Property C140KVA As Nullable(Of Decimal)
    Public Property C143KVA As Nullable(Of Decimal)
    Public Property C146KVA As Nullable(Of Decimal)
    Public Property C149KVA As Nullable(Of Decimal)
    Public Property C150ENCLOSURE As String
    Public Property C160ENCLTYPE As String
    Public Property C170PRODPROMI As Nullable(Of Date)
    Public Property C180ENGINE As String
    Public Property C185ENGINEBR As String
    Public Property C190LENGTHDEP As Nullable(Of Decimal)
    Public Property C191WIDTH As Nullable(Of Decimal)
    Public Property C192HEIGHT As Nullable(Of Decimal)
    Public Property C195LENGTHDEP As Nullable(Of Decimal)
    Public Property C196WIDTH As Nullable(Of Decimal)
    Public Property C197HEIGHT As Nullable(Of Decimal)
    Public Property C198VOLUME As Nullable(Of Decimal)
    Public Property C200CTRLPANEL As String
    Public Property C210LIFTPOINT As String
    Public Property C220ALTERNATO As String
    Public Property C230BATTERY As String
    Public Property C240SILENCER As String
    Public Property C250STONEGUAR As String
    Public Property C260EPA As String
    Public Property C270FUELTANK As String
    Public Property C280NEL1 As String
    Public Property C400PRODPROMI As Nullable(Of Date)
    Public Property C410ETAPORT As Nullable(Of Date)
    Public Property C420INSHOP As Nullable(Of Date)
    Public Property C430OKTOSHIP As Nullable(Of Date)
    Public Property C440PICKUP As Nullable(Of Date)
    Public Property C450STARTUP As Nullable(Of Date)
    Public Property C501OPTION1 As String
    Public Property C501OPTION2 As String
    Public Property C501OPTION3 As String
    Public Property C501OPTION4 As String
    Public Property C501OPTION5 As String
    Public Property C550VENDORVIN As String
    Public Property C600DESPATCH As String
    Public Property C605FACTRYREF As String
    Public Property C608DOCSDATE As Nullable(Of Date)
    Public Property C610CONTAINER As String
    Public Property C620BL As String
    Public Property C630ISF As String
    Public Property C640CARRIER As String
    Public Property C640CARRIER2 As String
    Public Property C800TRESVDATE As Nullable(Of Date)
    Public Property C810TRESVSLP As String
    Public Property C850TRESVNOTE As String
    Public Property C900NOTES As String
    Public Property ARRIVALDATE As Nullable(Of Date)
    Public Property LOCATION As String
    Public Property ST As String
    Public Property DATESORT As Nullable(Of Date)
    Public Property CATSORT As String
    Public Property WATSORT As Nullable(Of Decimal)
    Public Property RESVFORORD As Short
    Public Property RESVFORORD_DESC As String
    Public Property STATUS_DESC As String
    Public Property STATUS As Short
    Public Property PO_DOCNUM As String
    Public Property PO_TRANSDATE As Nullable(Of Date)
    Public Property PO_RCPNUMBER As String
    Public Property PO_PONUMBER As String
    Public Property PO_VDCODE As String
    Public Property PO_VDNAME As String
    Public Property PO_INVNUMBER As String
    Public Property PO_INVDATE As Nullable(Of Date)
    Public Property SO_ORDUNIQ As Nullable(Of Decimal)
    Public Property SO_LINENUM As Nullable(Of Short)
    Public Property SO_ORDNUMBER As String
    Public Property SO_CUSTOMER As String
    Public Property SO_BILNAME As String
    Public Property SO_SHPNAME As String
    Public Property SO_PONUMBER As String
    Public Property SO_ORDDATE As Nullable(Of Date)
    Public Property LISTPRICE As Nullable(Of Decimal)
    Public Property CATEGORY As String
    Public Property CNTLACCT As String
    Public Property ASSETCOST As Decimal
    Public Property C640CARRIER3 As String
    Public Property C645VESSEL As String
    Public Property C645VESSEL2 As String
    Public Property C645VESSEL3 As String
    Public Property C648VOYAGE As String
    Public Property C650PORTORIG As String
    Public Property C660CF214 As String
    Public Property C665IT7512IN As String
    Public Property C670IMPORTENT As String
    Public Property C700BOOKINGNO As String
    Public Property C710IE7512 As String
    Public Property C713TE7512 As String
    Public Property C716IT7512OUT As String
    Public Property C720PORTLOAD As String
    Public Property C730CONTAINER As String
    Public Property C735SEALNO As String
    Public Property C740OCEANCARR As String
    Public Property C744VESSELNAM As String
    Public Property C748VOYAGE As String
    Public Property C750EXPORTBL As String
    Public Property C760PORTDEST As String
    Public Property SALESPER1 As String
    Public Property C193WEIGHTKG As String
    Public Property C199WEIGHITEM As String
    Public Property C221ALTMODEL As String
    Public Property C300COUNTRYOR As String
    Public Property C301COOSERIAL As String
    Public Property C951CUSTSECT1 As String
    Public Property C952CUSTSECT2 As String
    Public Property C124AMPSGEN As String
    Public Property C880USD005 As String
    Public Property C880USD010 As String
    Public Property C880USD020 As String
    Public Property C880USD030 As String
    Public Property C880USD040 As String
    Public Property C880USD050 As String
    Public Property C880USD060 As String
    Public Property C880USD070 As String
    Public Property C880USD002 As String
    Public Property C880USDDATE As Nullable(Of Date)

End Class
