'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vUserPer
    Public Property User_UserId As Integer
    Public Property User_FirstName As String
    Public Property User_LastName As String
    Public Property User_Logon As String
    Public Property User_Per_Admin As Nullable(Of Integer)
    Public Property user_IC_History As Integer
    Public Property user_IC_Inquiry As Integer
    Public Property user_IC_Items As Integer
    Public Property user_IC_Price As Integer
    Public Property user_IC_ShowCost As Integer
    Public Property user_IC_SN As Integer
    Public Property user_IC_DefaultPage As String
    Public Property user_per_600 As Integer
    Public Property user_per_880 As Integer

End Class
